#!/usr/bin/env python3
"""Generate Sphinx pages mirroring NOS3 directories and grouping sibling files."""

from __future__ import annotations

import argparse
import codecs
import json
import os
import tempfile
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import DefaultDict, Dict, List, Optional, Sequence, Set, Tuple


CONTENT_OMIT_DIRS = {".git", "__pycache__", "build", "node_modules"}
CHUNK_SIZE = 64 * 1024
MANIFEST_NAME = ".nos3_inventory_manifest.json"
MARKER = "<!-- Generated by tools/generate_nos3_inventory.py; do not edit. -->"


@dataclass
class Entry:
    path: Path
    relative: PurePosixPath
    is_directory: bool
    link_target: Optional[str] = None
    content_status: Optional[str] = None


def is_generated(relative: PurePosixPath) -> bool:
    return any(part in CONTENT_OMIT_DIRS for part in relative.parts[:-1])


def is_utf8_text(path: Path) -> bool:
    decoder = codecs.getincrementaldecoder("utf-8")()
    try:
        with path.open("rb") as source:
            while chunk := source.read(CHUNK_SIZE):
                if b"\0" in chunk:
                    return False
                decoder.decode(chunk)
        decoder.decode(b"", final=True)
    except UnicodeDecodeError:
        return False
    except OSError as error:
        raise OSError(f"Cannot inspect {path}: {error}") from error
    return True


def collect_entries(root: Path, output: Path) -> List[Entry]:
    entries: List[Entry] = []
    output_resolved = output.resolve()

    def visit(directory: Path, relative: PurePosixPath) -> None:
        try:
            children = sorted(os.scandir(directory), key=lambda item: item.name.casefold())
        except OSError as error:
            raise OSError(f"Cannot list {directory}: {error}") from error

        for child in children:
            child_path = Path(child.path)
            child_relative = relative / child.name
            if child_path.resolve() == output_resolved:
                continue
            try:
                if child.is_symlink():
                    entries.append(
                        Entry(
                            child_path,
                            child_relative,
                            False,
                            link_target=os.readlink(child_path),
                            content_status="symlink",
                        )
                    )
                elif child.is_dir(follow_symlinks=False):
                    entries.append(Entry(child_path, child_relative, True))
                    visit(child_path, child_relative)
                elif child.is_file(follow_symlinks=False):
                    status = "generated" if is_generated(child_relative) else (
                        "text" if is_utf8_text(child_path) else "binary"
                    )
                    entries.append(
                        Entry(child_path, child_relative, False, content_status=status)
                    )
                else:
                    entries.append(
                        Entry(child_path, child_relative, False, content_status="special file")
                    )
            except OSError as error:
                raise OSError(f"Cannot inspect {child_path}: {error}") from error

    visit(root, PurePosixPath())
    return entries


def directory_page(output: Path, entry: Optional[Entry]) -> Path:
    if entry is None:
        return output / "index.md"
    return output / Path(*entry.relative.parts) / "index.md"


def relative_doc(from_page: Path, to_page: Path) -> str:
    relative = os.path.relpath(to_page, start=from_page.parent)
    return Path(relative).as_posix()[:-3]


def inline_code(value: str) -> str:
    longest = 0
    current = 0
    for character in value:
        if character == "`":
            current += 1
            longest = max(longest, current)
        else:
            current = 0
    delimiter = "`" * (longest + 1)
    padding = " " if value.startswith("`") or value.endswith("`") else ""
    return f"{delimiter}{padding}{value}{padding}{delimiter}"


def render_directory_page(
    entry: Optional[Entry],
    root: Path,
    output: Path,
    children: Sequence[Entry],
    text_file_count: int,
    total_count: int,
) -> str:
    directory_path = PurePosixPath() if entry is None else entry.relative
    label = directory_path.as_posix() + "/" if entry else root.name + "/"
    lines = [
        MARKER,
        "# NOS3 파일 인벤토리",
        "",
        f"**경로:** {inline_code(label)}",
        "",
    ]
    if entry is None:
        lines.extend(
            [
                f"- 전체 항목: {total_count:,}",
                f"- UTF-8 텍스트 파일 본문 포함: {text_file_count:,}",
                "- 빌드 산출물·바이너리·특수 파일은 경로만 표시합니다.",
                "- 심볼릭 링크는 대상 경로만 표시하며, 링크 대상은 따라가지 않습니다.",
                "",
            ]
        )
    directories = sorted(
        (child for child in children if child.is_directory),
        key=lambda child: (child.path.name.casefold(), child.path.name),
    )
    if directories:
        lines.extend(["## 하위 폴더", "", "```{toctree}", ":maxdepth: 1", ""])
        current_page = directory_page(output, entry)
        for child in directories:
            lines.append(relative_doc(current_page, directory_page(output, child)))
        lines.extend(["```", ""])

    files = sorted(
        (child for child in children if not child.is_directory),
        key=lambda child: (child.path.name.casefold(), child.path.name),
    )
    if files:
        lines.extend(["## 이 폴더의 파일", ""])
        for child in files:
            lines.extend(render_file_section(child))
    else:
        lines.extend(["이 폴더에는 직접 포함된 파일이 없습니다.", ""])
    return "\n".join(lines)


def render_file_section(entry: Entry) -> List[str]:
    lines = [
        f"### {inline_code(entry.path.name)}",
        "",
        f"**경로:** {inline_code(entry.relative.as_posix())}",
        "",
    ]
    if entry.link_target is not None:
        lines.extend(
            [
                f"심볼릭 링크 대상: {inline_code(entry.link_target)} (대상 미포함)",
                "",
            ]
        )
    elif entry.content_status == "generated":
        lines.extend(["빌드 또는 생성 디렉터리의 항목입니다. 본문은 생략했습니다.", ""])
    elif entry.content_status == "binary":
        lines.extend(["바이너리 파일입니다. 본문은 생략했습니다.", ""])
    elif entry.content_status == "special file":
        lines.extend(["일반 파일이 아닌 특수 파일입니다. 본문은 생략했습니다.", ""])
    else:
        fence = markdown_fence(entry.path)
        content_chunks: List[str] = []
        try:
            with entry.path.open("r", encoding="utf-8", newline="") as source:
                while chunk := source.read(CHUNK_SIZE):
                    content_chunks.append(chunk)
        except (OSError, UnicodeDecodeError) as error:
            raise OSError(f"Cannot read text file {entry.path}: {error}") from error
        content = "".join(content_chunks)
        code_block = f"{fence}{language_for(entry.path)}\n{content}"
        if content and not content.endswith(("\n", "\r")):
            code_block += "\n"
        code_block += fence
        lines.extend(["", code_block, ""])
    return lines


def markdown_fence(path: Path) -> str:
    longest = 0
    current = 0
    with path.open("rb") as source:
        while chunk := source.read(CHUNK_SIZE):
            for value in chunk:
                if value == ord("`"):
                    current += 1
                    longest = max(longest, current)
                else:
                    current = 0
    return "`" * max(3, longest + 1)


def language_for(path: Path) -> str:
    if path.name == "CMakeLists.txt":
        return "cmake"
    if path.name in {"Makefile", "GNUmakefile"} or path.suffix.lower() == ".mk":
        return "make"
    return {
        ".c": "c",
        ".cc": "cpp",
        ".cpp": "cpp",
        ".cxx": "cpp",
        ".h": "c",
        ".hh": "cpp",
        ".hpp": "cpp",
        ".hxx": "cpp",
        ".py": "python",
        ".sh": "bash",
        ".cmake": "cmake",
        ".xml": "xml",
        ".html": "html",
        ".css": "css",
        ".js": "javascript",
        ".ts": "typescript",
        ".json": "json",
        ".yml": "yaml",
        ".yaml": "yaml",
        ".md": "markdown",
        ".rst": "rst",
        ".rb": "ruby",
        ".java": "java",
        ".fpp": "fpp",
    }.get(path.suffix.lower(), "text")


def atomic_write(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=path.parent,
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="") as output:
            output.write(contents)
        temporary_path.replace(path)
    except Exception:
        try:
            temporary_path.unlink()
        except FileNotFoundError:
            pass
        raise


def previous_generated_paths(output: Path) -> Set[str]:
    manifest = output / MANIFEST_NAME
    if not manifest.is_file():
        return set()
    try:
        data = json.loads(manifest.read_text(encoding="utf-8"))
        files = data["files"]
    except (OSError, json.JSONDecodeError, KeyError, TypeError) as error:
        raise ValueError(f"Invalid inventory manifest {manifest}: {error}") from error
    if not isinstance(files, list) or not all(isinstance(item, str) for item in files):
        raise ValueError(f"Invalid generated file list in {manifest}")
    return set(files)


def generate(root: Path, output: Path) -> Tuple[int, int, int]:
    entries = collect_entries(root, output)
    children_by_parent: DefaultDict[str, List[Entry]] = defaultdict(list)
    directories: List[Optional[Entry]] = [None]
    for entry in entries:
        children_by_parent[entry.relative.parent.as_posix()].append(entry)
        if entry.is_directory:
            directories.append(entry)
    text_count = sum(entry.content_status == "text" for entry in entries)
    planned: Dict[Path, Optional[Entry]] = {}
    for directory in directories:
        directory_relative = PurePosixPath() if directory is None else directory.relative
        planned[directory_page(output, directory)] = directory

    old_paths = previous_generated_paths(output)
    output.mkdir(parents=True, exist_ok=True)
    for path, directory in planned.items():
        directory_relative = PurePosixPath() if directory is None else directory.relative
        contents = render_directory_page(
            directory,
            root,
            output,
            children_by_parent[directory_relative.as_posix() or "."],
            text_count,
            len(entries),
        )
        atomic_write(path, contents)

    new_paths = {path.relative_to(output).as_posix() for path in planned}
    for stale in old_paths - new_paths:
        stale_path = (output / stale).resolve()
        if output.resolve() not in stale_path.parents:
            raise ValueError(f"Refusing to remove path outside inventory: {stale}")
        if stale_path.is_file():
            stale_path.unlink()
    manifest_contents = json.dumps(
        {"files": sorted(new_paths)},
        ensure_ascii=False,
        indent=2,
    ) + "\n"
    atomic_write(output / MANIFEST_NAME, manifest_contents)
    return len(entries), text_count, len(directories)


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate one Sphinx page per directory in a NOS3 checkout. "
            "Files in the same directory are combined on that directory's page."
        )
    )
    parser.add_argument("root", type=Path, help="Path to the NOS3 checkout")
    parser.add_argument(
        "--output",
        type=Path,
        help="Documentation output directory (default: ./project_inventory)",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    arguments = parse_args(argv)
    root = arguments.root.expanduser().resolve()
    if not root.is_dir():
        raise NotADirectoryError(f"NOS3 root is not a directory: {root}")
    output = arguments.output or Path.cwd() / "project_inventory"
    output = output.expanduser().resolve()
    if output == root or root in output.parents:
        raise ValueError("Documentation output must not be inside the NOS3 source tree")
    path_count, text_count, page_count = generate(root, output)
    print(
        f"Wrote {output} ({path_count:,} source paths; "
        f"{text_count:,} text files; {page_count:,} pages)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
